### ISSUE TITLE
Issue: Intervals Persist After Worker Restart in JavaScript Service

### ISSUE THREAD

**Issue by Rainkenpor** [totaljs/flow#123]
We are experiencing an issue where intervals in a JavaScript service continue to run even after restarting the worker. This behavior causes duplicate executions of the same logic and may lead to resource exhaustion or unexpected behavior in the service.

**Comment by petersirka** [comment]
Not possible. When the worker is restarted, the entire process is killed and then restarted. Can you make an example with the mentioned problem?

**Comment by Rainkenpor** [comment]
https://github.com/user-attachments/assets/a6052d2c-c861-4c8d-8f91-c2cbe0e4727f

**Comment by petersirka** [comment]
This is not a flow problem. The problem is on your side, because the `code' component evaluates its custom code for every incoming message. The `code' component allows you to define everything. If you want to do a delay or something else, use a `delay' component or create a new one according to your needs.

**Comment by Rainkenpor** [comment]
Thank you for your response!
