### ISSUE TITLE
[FLOW] Cluster Question

### ISSUE THREAD

**Issue by KangGS** [totaljs/flow#25]
We have removed the following description for the update now.
// @TODO: sync && F.cluster.emit('flow.cluster.execute', filename);

Has the cluster plan terminated?

**Comment by petersirka** [comment]
My plan is to create mother of Flow :-D :-D .... App like [SuperAdmin](https://www.totaljs.com/superadmin/) but for multiple Flows. Beacuse our customers use multiple independent Flows and they want to change them in the one place. So cluster version is terminated now because it's not good idea for processing. We will see.

**Comment by geunsukang** [comment]
Thank you !
