### ISSUE TITLE
Question: Is there any way to use names for the ports instead of numbers?

### ISSUE THREAD

**Issue by Vodoprovod4ika** [totaljs/flow#57]
Pretty much my question is on the title. When I add or remove ports in old component then I need to rearrange my component.on('0'... 1, 2, 3 etc. 
And component.send should be changed too...

**Comment by petersirka** [comment]
Currently this isn't possible. Outputs/Inputs can be only indexes instead of identifiers. So if you remove a point then indexes are moved too.

We recommend to keep fixed count of outputs/inputs. Yes names can solve this problem, but implementation is a bit complicated (I have implemented it to [j-Flow client-side component](https://componentator.com/components/j-flow/) only). Of course we can think about it but currently we don't have any case for it :-)

**Comment by Vodoprovod4ika** [comment]
So I have one idea as workaround but not sure if this will work. I can make helper to return index based on parent/child name using: 

component.outputs();
component.inputs();

**Comment by petersirka** [comment]
This feature will be maybe part of Total.js Flow v7 optimized for Total.js 4. We will see.
