### ISSUE TITLE
Flow V10 and the use of default_root

### ISSUE THREAD

**Issue by paul-v-g** [totaljs/flow#69]
What a great product! Thanks for all your hard work!

I have a question cq. bug;
I tried setting default_root in config
That doesn't work :) There are several hard-coded references to the root
( and yes I've added a folder to public )
It loads the main page.
![image](https://user-images.githubusercontent.com/22495684/178767637-45b02080-df16-4a47-83fa-07685314dbee.png)

But the websocket can't connect and the views cannot be found
![image](https://user-images.githubusercontent.com/22495684/178767407-1b2745c9-b417-4bd3-ac05-57fe479cadea.png)

Should it work and is it a bug?
Or will you add support for the use of "default_root"
Thanks!

**Comment by petersirka** [comment]
Hi @paul-v-g, thank you, and we appreciate it. Unfortunately, the current Flow version is not optimized for changing the root path. But we will look at it current/next month, OK?

**Comment by paul-v-g** [comment]
Anything you could do would be great!
Thanks :)

**Comment by petersirka** [comment]
Hi @paul-v-g,
I have updated Flow, and you need to download it again (if you use bundle, then download the .bundle only). After that, you need to update the Total.js framework $ npm install total4@beta because I found a bug with inline merging files directly in the view engine and enabled default_root. The Beta version should be stable, and it contains only fixes:
https://github.com/totaljs/framework4/blob/master/changelog.txt#L2

Let me know.
