### ISSUE TITLE
Creating a new code component issues with outputs being set correctly

### ISSUE THREAD

**Issue by ColtonMcInroy** [totaljs/flow#82]
When adding a new code component simply adjusting the number of outputs and saving does not work correctly. I have not done extensive testing, but generally I have to save the workflow, then edit the code component in a way that allows me to save it again, then when it saves finally it updates. Sometimes I have to try it a couple times. Not sure if it makes a difference, but I am using Brave (chromium).

**Comment by petersirka** [comment]
@ColtonMcInroy We have released updated components today, but you must update Flow (or replace a link in the Settings) because I have kept the old components (on CDN) due to backward compatibility.

**NEW:**
https://cdn.totaljs.com/flowstream/webcomponents/db.json

**OLD:**
https://cdn.totaljs.com/flowstream/components/db.json

**Comment by Will-create** [comment]
@ColtonMcInroy  Is this issue still open?

**Comment by ColtonMcInroy** [comment]
Yes, does look like it has been fixed. It does look like the same issue occurs with the Switch component though.
