### ISSUE TITLE
Feature: Annotations on canavs.

### ISSUE THREAD

**Issue by wildone** [totaljs/flow#85]
Currently, a default component called Group can be placed on canvas to combine flow elements.

It would be great to have another default component called Label to allow adding rich text to the canvas.

There is a Comment component but it needs to be discovered before its apparent how to add annotations to canvas. Also it does not output text similar to what Group does.

**Comment by petersirka** [comment]
Hi @wildone. Sorry for the delay. I overlooked this issue. There are two differences. Groups are internal, they are not components, and they are part of the Flow schema. I understand that it would be better to add something like Labels under Groups, but it's very complicated.

Maybe I should create a Label component (it will look like an internal label), but it will still not be like a group, it will be a standard component without inputs/outputs. The problem is that we can't integrate it into the Flow, so users must know about it.
